SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 950
FONT_SIZE = 30
FPS = 120
STAGE_TIME_RATE = 10
STAGE_SPAWN_MULTI = 0.15

PLAYER_RADIUS = 20.0
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 250
PLAYER_SPEED = 250
PLAYER_SHOOT_SPEED = 1200
PLAYER_SHOOT_COOLDOWN = 0.17
SHOT_RADIUS = 9
SHIELD_PULSE_SPEED = 2000
SHIELD_PULSE_RECHARGE_AMOUNT = 20
POWER_UP_MULTI = 2
POWER_UP_CHANCE = 0.1
POWER_UP_TIME = 5

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 4
ASTEROID_SPAWN_RATE = 1
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
