SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 144
STAGE_TIME_RATE = 10
STAGE_SPAWN_MULTI = 0.2

PLAYER_RADIUS = 20.0
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 250
PLAYER_SPEED = 150
PLAYER_SHOOT_SPEED = 1200
PLAYER_SHOOT_COOLDOWN = 0.16
SHOT_RADIUS = 7
SHIELD_PULSE_SPEED = 2000
SHIELD_PULSE_RECHARGE_AMOUNT = 15
POWER_UP_MULTI = 2
POWER_UP_CHANCE = 0.1
POWER_UP_TIME = 7

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
